# Change these first
owner: traist-web-services # Your GitHub username
repo: service-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Traist
    url: https://traist.co.uk
  - name: Budapest Pulse
    url: https://budapestpulse.com
  - name: Team Are Online
    url: https://team-are.online
  - name: Joe Innes
    url: https://joeinn.es
  - name: Mum's Gin
    url: https://mumsgin.com
  - name: Ada & Joe
    url: https://ada-joe.com
  - name: Ackee
    url: https://analytics.traist.co.uk
  - name: Tastine
    url: https://tastine.ada-joe.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.traist.co.uk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/traist-web-services/traist/main/public/favicon.ico
  name: Traist Service Status
  introTitle: "**Service Status** updates for sites and apps hosted by Traist Web Services"
  introMessage: "This page details active outage details and uptime for services and sites hosted within Traist Web Service's cloud. Normal response times are between [324 and 1100 ms](https://www.littledata.io/average/server-response-time)."
  navbar:
    - title: Status
      href: /
    - title: Traist Home Page
      href: https://traist.co.uk
robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/2 * * * *"
  
user-agent: traist-web-services
